/*
 * #%L
 * vertx-pojo-mapper-common
 * %%
 * Copyright (C) 2017 Braintags GmbH
 * %%
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * #L%
 */
package de.braintags.vertx.jomnigate.mapping.impl.keygen;

import de.braintags.vertx.jomnigate.mapping.IKeyGenerator;

/**
 * A Key is generated by an {@link IKeyGenerator} and contains the generated key
 * 
 * @author Michael Remme
 * 
 */
public class Key {
  private Object generatedKey;

  /**
   * 
   * @param key
   *          the native value of the key
   */
  public Key(Object key) {
    this.generatedKey = key;
  }

  /**
   * Get the generated key
   * 
   * @return
   */
  public Object getKey() {
    return generatedKey;
  }
}
